# Generated by Django 6.0.4 on 2026-04-15 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qr', '0005_qrcode_last_scanned_at_qrcode_scan_count_qrscan'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrcode',
            name='name',
            field=models.CharField(blank=True, default='My QR Code', max_length=255),
        ),
    ]
